export const storeConfig = {
  name: process.env.NEXT_PUBLIC_STORE_NAME || 'Pavan Sai Kirana General Store',
  shortName: 'Pavan Sai',
  description: 'Fast local delivery for your everyday grocery needs.',
  phone: process.env.NEXT_PUBLIC_STORE_PHONE || '+91XXXXXXXXXX',
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '91XXXXXXXXXX',
  minimumOrderValue: Number(process.env.NEXT_PUBLIC_MINIMUM_ORDER_VALUE) || 200,
  deliveryMessage: process.env.NEXT_PUBLIC_DELIVERY_MESSAGE || 'Target delivery time: 30 minutes',
  storeAddress: process.env.NEXT_PUBLIC_STORE_ADDRESS || 'Store address to be configured',
  currency: '₹',
  orderIdPrefix: 'PSK',
  deliveryCharge: 0,
  tagline: 'Your Everyday Groceries, Delivered to Your Door',
  features: [
    { icon: '🛵', title: '30 Mins', subtitle: 'Target Delivery', detail: 'Fast local drop' },
    { icon: '₹200', title: 'Min', subtitle: 'Minimum Order', detail: 'Small basket friendly', isText: true },
    { icon: '💬', title: 'WhatsApp', subtitle: 'Direct Support', detail: 'Order verification' },
    { icon: '📲', title: 'Pay UPI', subtitle: 'Pay on Delivery', detail: 'GPay, PhonePe, Paytm' },
  ],
  colors: {
    primary: '#F98866',
    primaryDark: '#e56b46',
    primaryDeep: '#c24b27',
    secondary: '#FFF2D7',
    bg: '#FFFDF9',
    card: '#FFFFFF',
    text: '#211B14',
    textLight: '#56423d',
    green: '#15803d',
    greenLight: '#dcfce7',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
  },
} as const;
